version: "3.8"

services:
  dev:
    build:
      context: docker/dev
    container_name: sample-grpc-server-with-go-dev
    tty: true
    volumes:
      - ./volumes:/volumes

  production:
    image: sample-grpc-server-with-go:v1.0.0
    container_name: sample-grpc-server-with-go-prod
    tty: true